"""AI-authorship disclosure for CW-generated public artifacts (chief-wiggum#317).

CW is MIT-licensed and public, so its Art. 2(12) FOSS exemption from the EU AI
Act holds unless Art. 5 or Art. 50 applies. Art. 50(2) (machine-readable
marking of AI-generated synthetic text) is the one genuinely arguable limb —
CW authors commit messages, PR bodies, and issue bodies from scratch and
publishes them into a public GitHub repo. Rather than resolve whether Art.
50(2) catches that (an open legal question, recorded as ``TBD:`` in
``docs/ai-act-posture.md`` for sign-off), CW moots it: disclose AI authorship
on every generated commit, PR body, and issue body. Mooting the question in
practice is not the same as answering it — the underlying determination stays
open.

Two artifact shapes, two helpers:

- ``ensure_disclosure`` — a markdown line appended to PR/issue bodies.
- ``ensure_commit_trailer`` — a git-trailer-shaped line appended to commit
  messages (blank line, then ``Key: value``, following the ``Co-Authored-By:``
  convention git tooling already parses).

Both are idempotent: calling them twice on the same text does not duplicate
the line, so they are safe to run at more than one point in a pipeline.
"""

from __future__ import annotations

#: Appended to CW-generated PR and issue bodies published to a public repo.
DISCLOSURE_LINE = (
    "*Generated by chief-wiggum, an AI system, per its Article 50 disclosure "
    "posture — see [docs/ai-act-posture.md]"
    "(https://github.com/plwp/chief-wiggum/blob/main/docs/ai-act-posture.md).*"
)

#: Appended as a git trailer to CW-generated commit messages.
COMMIT_TRAILER = "Generated-by: chief-wiggum (AI system; see docs/ai-act-posture.md)"


def ensure_disclosure(body: str, line: str = DISCLOSURE_LINE) -> str:
    """Return ``body`` with ``line`` appended, unless already present."""
    if line in body:
        return body
    sep = "" if body.endswith("\n") else "\n"
    return f"{body}{sep}\n{line}\n"


def ensure_commit_trailer(message: str, trailer: str = COMMIT_TRAILER) -> str:
    """Return ``message`` with ``trailer`` appended as a git trailer, unless present."""
    if trailer in message:
        return message
    sep = "" if message.endswith("\n") else "\n"
    return f"{message}{sep}\n{trailer}\n"
